### ISSUE TITLE
CultureInfo issue

### ISSUE THREAD

**Issue by xrobrobx** [bsclifton/Clifton.Payment#2]
An exception keeps throwing saying that the year cannot be converted to a four digit year.

The CultureInfo appears to be incorrect. The argument should be "en-US" as opposed to just "US".

**Comment by xrobrobx** [comment]
Nevermind, I think somehow during compilation it modified it.

**Comment by bsclifton** [comment]
Glad it worked out! Let me know how you like it- pull requests are very welcome if you wanted to add any functionality
