### ISSUE TITLE
Payeezy Gateway: Security Protocol Update to TLS v1.2

### ISSUE THREAD

**Issue by ssddsean** [bsclifton/Clifton.Payment#6]
The API stopped working last week, returning 500 Internal Server Error.
Contacted the Payeezy team yesterday, and they advised us to ensure HTTP headers we’re negotiating the connection with TLS 1.2 only.

Added the line below inside of CreateRequest function and it fixed the issue
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

Just a FYI, curious if there's any other ways to go around it.

Below is the link that notifies the enforcement of TLS v1.2
https://support.payeezy.com/hc/en-us/articles/115002769907-Payeezy-Gateway-Security-Protocol-Update-to-TLS-v1-2

**Comment by bsclifton** [comment]
@ssddsean sounds like an easy fix- would you be interested in opening a pull request?

**Comment by bsclifton** [comment]
Fixed with https://github.com/bsclifton/Clifton.Payment/pull/7
